# Generated by Django 4.0.4 on 2022-06-13 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('disponible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('comentario', models.CharField(max_length=500)),
                ('fecha_prestamo', models.DateTimeField(verbose_name='fecha prestamo')),
                ('fecha_devuelto', models.DateTimeField(verbose_name='fecha devuelto')),
                ('devuelto', models.BooleanField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
        ),
    ]
