# Generated by Django 4.0.4 on 2022-06-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_prestamo_fecha_devuelto'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='comentario',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='item',
            name='fecha_prestamo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha prestamo'),
        ),
        migrations.AddField(
            model_name='item',
            name='usuario',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='prestamo',
        ),
    ]
