# Generated by Django 4.0.4 on 2022-06-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_item_comentario_item_fecha_prestamo_item_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.CharField(choices=[('computador', 'computador'), ('juego', 'juego'), ('otros', 'otros'), ('accesorios', 'accesorios')], max_length=100),
        ),
        migrations.DeleteModel(
            name='categoria',
        ),
    ]
