# Generated by Django 4.0.5 on 2022-06-15 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_delete_prestamo'),
    ]

    operations = [
        migrations.CreateModel(
            name='prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(blank=True, null=True, verbose_name='fecha prestamo')),
                ('fecha_devuelto', models.DateTimeField(blank=True, null=True, verbose_name='fecha devuelto')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.usuario')),
            ],
        ),
    ]
