# Generated by Django 4.0.5 on 2022-06-15 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_prestamo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='fecha_prestamo',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='logo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
