# Generated by Django 4.0.5 on 2022-06-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_prestamo_devuelto'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='codigo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
