# Generated by Django 4.0.5 on 2022-06-17 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-nombre']},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['-nombre']},
        ),
    ]
